# To disable database DAO, set driver: none. All output will then be to file, exclusively.
# Don't mess with these lightly. 

configuration_file_version: 1

# Turns on console output for certain backend tasks (such as asynch commits) and statistics
debug: true

# Gadget "base templates" defining type, costs, and upgrades are in flat files
gadget_template_folder: Contraptions/gadgets/

dao:
  database:
    driver: mysql
    host:
    port: 2306
    username:
    password:
    database: contraptions
    schema:
  cache:
    gadgets: 100000
    states: 10000
    # Eviction strategy: lru, mru, lfu, mfu, random, smallest, largest 
    strategy: lfu

# Controls monitor defaults, applies to all monitors
monitor:
  # Number of monitor threads to run
  count: 4
  # How to partition contraptions between monitors -- round_robin, round_robin_fair, random
  strategy: round_robin
  # How often to update each contraption, in ticks. When a contraption is updated is controlled by this, count, strategy, and rolling_updates
  update_frequency: 10
  # Should a fully unloaded contraption be run -- false, means no, true means yes.
  run_unloaded: true
  # if set true, splits gadgets/contraptions into pools that are updated every tick in a rolling fashion -- might help prevent sudden lag spikes
  rolling_updates: false

